### PR TITLE
Integrate Xen-api docs

### PR DESCRIPTION
**Pull request by robhoes**
Still a bit rough, and the js/css etc could be improved (just copied most of it
from the existing xen-api site).

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
Why did we need to shuffle the layouts around? Was the javascript that was adding those styles to the table clashing with the css you've added?

**Comment by robhoes** [comment]
@simonjbeaumont Yes, it added `table-striped` etc to _all_ tables, but it was not suitable on all tables, in particular in the way they are currently used on the API pages.

**Comment by djs55** [comment]
I'm impatient -- it's been 3 minutes already since the last comment. Can this be merged??

**Comment by simonjbeaumont** [comment]
Yes, unfortunately I had to do this after the page had loaded since the table HTML is generated from markdown and cannot be annotated with the "appropriate" CSS classes. How bad does the API section look with this class?

Also, since the Xapi section talks about exposing the XenAPI and has a page about API evolution, maybe the XenAPI page would be better suited under this section in the navbar?

**Comment by robhoes** [comment]
I think it is a little too restrictive to force all tables to have the same CSS class on it. In this case it added borders and alternating row colours, which made it look quite bad. Having said that, these XenAPI pages could probably do with bootstrapification to make things fit a little better. But I just wanted to get stuff out there first.

On your second point, I thought it would be nice to have one high-level section for API-related docs, including the evolution docs. I am thinking about including better information about how to use the XenAPI, plus examples. There is a lot of useful text in the PDF version of the XenAPI docs, and the SDK guide at the moment, which I was planning to put here, and extend. I think the xapi and other daemon-specific sections could be more architecture and implementation focused.

What do you think?

**Comment by robhoes** [comment]
:)

**Pull request merged**
