### PR TITLE
CA-215078: Added missing branding.

### PR DESCRIPTION
**Pull request by kc284**
Also removed unreachable breaks.

Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
Hmm... I don't think that this file is used anymore...

**Comment by kc284** [comment]
Indeed, I had another look around and it's only referenced from index-old.html, which is not used either, so both of them can be removed.

**Comment by robhoes** [comment]
I think that more files can go:
- assets/css/xenapi.css
- assets/js/apidoc.js
- all of xen-api/api

**Comment by robhoes** [comment]
Also, Travis complains:
```
- ./_site/baseurl_travis_test/xen-api/evolution.html
  *  External link http://wiki.eclipse.org/Eclipse/API_Central/Deprecation_Policy failed: 404 No error
htmlproofer 3.0.5 | Error:  HTML-Proofer found 1 failure!
```
This is not due to this PR, but might as well fix it (remove the offending URL) to get the tests passing again.

**Comment by kc284** [comment]
The complaint from Travis is not consistent. To start with, the URL does exist, however sometimes the proofer can find it, while some others it can’t. I set it up on my local machine too and ran the checks locally and the behaviour is the same. Instead of removing the URL completely, it may be worth investigating why we have this inconsistent behaviour.

**Comment by kc284** [comment]
The stylesheet cannot go completely because it provides the formatting for the field and message tables on the class pages.

**Comment by kc284** [comment]
Just for the records, there is a layout issue on the page with the changes for the orlando release due to a message having a very long name; this is neither caused nor fixed by this particular PR.

**Comment by robhoes** [comment]
> The stylesheet cannot go completely because it provides the formatting for the field and message tables on the class pages.

Could you not move all of xenapi.css to docs.css? I think that you have now removed all of the links to xenapi.css, so it does not seem used anymore?

**Comment by kc284** [comment]
There is still a reference to the xenapi.css in the xenapi-class.html a bit further down from the one I removed (that was a duplicate).
It's not strictly necessary to merge xenapi.css into doc.css, but if it's too annoying I'll do it (I just thought we're going a bit out of the original scope of this PR).

**Comment by robhoes** [comment]
Oh, I didn't spot the duplicate. I agree it is "out of scope", but it would avoid confusion later.

**Comment by kc284** [comment]
Ok, let's leave this open and I'll get back to it when I run out of urgent things to do :)

**Comment by robhoes** [comment]
I'm going to merge this now. We can do further fixes in a new PR.

**Pull request merged**
