### PR TITLE
Additions to xapi part of GPU evolution design

### PR DESCRIPTION
**Pull request by johnelse**
Add some details on how we will store assignments of vGPUs to pGPUs at
VM start time.

### CODE REVIEW

**Comment by robhoes** [comment]
Since this changes an existing (and "confirmed" doc): bump the version number?

**Comment by robhoes** [comment]
Perhaps adding a "what has changed in version _x_" table is useful to include (in general for all docs).

**Comment by johnelse** [comment]
Good idea!

**Comment by johnelse** [comment]
I've added generic support for revision history tables (as well as added a table for this doc). Looks like ruby is falling over though :(

**Comment by robhoes** [comment]
Nice! It works on my machine...

**Comment by robhoes** [comment]
Regarding the design itself: would this entirely remove the use of platform keys, and also fix the "cannot start multiple VMs at once" issues?

**Comment by johnelse** [comment]
My machine too!

Yes, this would remove the use of platform keys. All the required data would be inferrable from the VGPU and VGPU_type fields. As long as VGPU.scheduled_to_be_resident_on is atomically switched to VGPU.resident_on (and is taken account of in capacity planning) this should eliminate the vGPU bootstorm races.

**Pull request merged**
