### PR TITLE
XenAPI docs updates as of xen-api/8ef12da17f300bd (includes XSO-974).

### PR DESCRIPTION
**Pull request by kc284**

### CODE REVIEW

**Comment by edwintorok** [comment]
Was this generated automatically, i.e. should we automate this?

**Comment by edwintorok** [comment]
Also bundler is unhappy for some reason

**Comment by kc284** [comment]
It used to be generated automatically by the job removed within https://github.com/xapi-project/xen-api/pull/4020. We should fix it at some point.
I'm not sure why bundler is complaining, the change is in the content.

**Comment by kc284** [comment]
It may be that the version of ruby is old (see https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html).

**Comment by psafont** [comment]
It should be re-added as some sort of first-class "publish" job, as opposed of being tucked away as part of some other process.

**Comment by kc284** [comment]
I'll look into re-adding it since I'm in the area.

**Pull request merged**
