### PR TITLE
XenAPI docs update to include release stockholm_psr and latest master changes.

### PR DESCRIPTION
**Pull request by kc284**
The contents of this PR have been autogenerated from master (`make doc-json`).

### CODE REVIEW

**Comment by kc284** [comment]
This needed a small change in xen-api too, PR to follow.

**Comment by psafont** [comment]
I'm thinking that a github workflow in xapi that opens PRs here would be ideal. I don't think we need to get the 2 reviewers if the changes are automated.

**Review by psafont — APPROVED** [review]

**Review by edwintorok — APPROVED** [review]
I see this adds some APIs available only in the 'next' release. Do we need an .md file for next?

**Comment by kc284** [comment]
There used to be one, but it was explicitly disabled with this PR https://github.com/xapi-project/xen-api/pull/3864/ because strictly speaking http://xapi-project.github.io/xen-api/releases.html lists released versions. However, the new API members will indeed appear under the various http://xapi-project.github.io/xen-api/classes/ and their individual doc will say they are still unreleased, i.e. the class pages reflect master. Do you have any concerns about the whole thing?

**Comment by psafont** [comment]
I don't think showing them as unreleased is a problem, maybe some outside perspective may help.

@olivierlambert Would you mind asking vates devs who use these docs what would they think about having unreleased fields and functions in the docs?

**Comment by olivierlambert** [comment]
IMHO being able to see things before they land in production is important as an API consumer (if I understood correctly the topic). Pinging @julien-f on that matter.

**Comment by kc284** [comment]
To clarify: unreleased API fields, functions etc. do appear in the docs, the question is whether to also show the entry "Unreleased" at the bottom of http://xapi-project.github.io/xen-api/releases.html, which will point to a page listing all the new members together. It's easy to bring back that page if it useful.

**Comment by olivierlambert** [comment]
I think I'd like to have this visible in the release page :)

**Pull request merged**
