### PR TITLE
Upgrade to bootstrap v3

### PR DESCRIPTION
**Pull request by robhoes**
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
See http://robhoes.github.io/xapi-project.github.io/

**Comment by jonludlam** [comment]
Aren't you supposed to be having a baby!?

**Comment by djs55** [comment]
Looks good to me!

On Wed, Jan 14, 2015 at 11:03 PM, Rob Hoes <notifications@github.com> wrote:

> See http://robhoes.github.io/xapi-project.github.io/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/xapi-project.github.io/pull/71#issuecomment-70010634>
> .
>



-- 
Dave Scott

**Comment by robhoes** [comment]
@jonludlam Yep, but there's lot's of waiting involved. Back home now... tomorrow may be the day :)

**Comment by robhoes** [comment]
Travis says "linking to internal hash # that does not exist". Must be due to `<a href="#">`. A little strict?

**Comment by simonjbeaumont** [comment]
>  tomorrow may be the day :)
Cool! Wishing you guys all the best!

In terms of this pull request...

Do we need the npm.js?

> Travis says "linking to internal hash # that does not exist". Must be due to <a href="#">. A little strict?
Well it's checking all the links... Do we need this link? Is it to take you to the top of the page? If so we could always use jquery.

Finally the typeface seems to have changed... Is this deliberate?

**Comment by robhoes** [comment]
I'm back :)

@simonjbeaumont:
* The font looks to same as before for me, but some of the heading's sizes have changed in the new bootstrap stylesheet (I am checking this in Safari).
* An `href="#"` attribute is sometimes used to create something that looks/behaves like a hyperlink (even though it does not go anywhere), so it can be styled as such by css. I'll see if I can eliminate it.
* npm.js comes from the new bootstrap release zip, which I just dumped in as-is. Not sure what it actually is or whether we are using it :)

**Comment by robhoes** [comment]
@simonjbeaumont: I've managed to make travis happy by eliminating the `href="#"`, and have also removed npm.js, which seems to be unnecessary.

**Comment by robhoes** [comment]
Here in firefox, the font still looks the same as before, though the headings are styled slightly differently (see http://robhoes.github.io/xapi-project.github.io/). I quite like it though. What do you think @simonjbeaumont ?

**Comment by robhoes** [comment]
Merging, as we seem to be mostly in agreement about this. I'll fix up any remaining issues if and when they come up.

**Pull request merged**
